spring.application.name=Chatter

#H2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:chatter
spring.datasource.username=chatter

#Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=chat-server-${random.uuid}
spring.kafka.consumer.auto-offset-reset=latest

#JSON
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.chatter.chatter.dto,*
spring.kafka.consumer.properties.spring.json.value.default.type=com.chatter.chatter.dto.ChatMessage